# Generated by Django 5.2 on 2025-07-09 20:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('technologies', ckeditor.fields.RichTextField()),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('demo_video', models.FileField(blank=True, null=True, upload_to='portfolio_videos/')),
                ('created_from', models.DateField()),
                ('created_to', models.DateField()),
            ],
        ),
    ]
