# Generated by Django 5.2 on 2025-07-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_about_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
